spring:
  datasource:
    url: ${PUPPIES-SERVICES_DATABASE_URL:jdbc:postgresql://localhost:5434/puppies}
    username: ${PUPPIES-SERVICES_DATABASE_USERNAME:postgres}
    password: ${PUPPIES-SERVICES_DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
  flyway:
    enabled: true
    url: ${PUPPIES-SERVICES_DATABASE_URL:jdbc:postgresql://localhost:5434/puppies}
    schemas: puppies-post-migration
    user: ${PUPPIES-SERVICES_DATABASE_USERNAME:postgres}
    password: ${PUPPIES-SERVICES_DATABASE_PASSWORD:password}
    locations: classpath:db/migration/postgresql
    table: puppies_post_schema_version
    out-of-order: true
    validate-on-migrate: true

application:
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 10

logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{5}){cyan} %clr(:){faint} %40(%clr([%M])) %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : [%M] : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
